databases:
  - name: next_crud_database
    databaseName: db_next_crud_database
    user: user_next_crud_database
    plan: free

services:
  - type: web
    name: next_crud_web
    buildCommand: "./bin/render-build.sh"
    startCommand: "pnpm run start"
    plan: free
    runtime: node
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: next_crud_database
          property: connectionString
      - key: NODE_VERSION
        value: 20.8.1
